"""add reset token fields to user

Revision ID: 298bf17e43fe
Revises: 2dc33bc17d86
Create Date: 2026-08-25 13:39:15.918607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298bf17e43fe'
down_revision = '2dc33bc17d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
